const AUTHENTICATION = 'AUTHENTICATION'
const VALIDATION = 'VALIDATION'
const NOTFOUND = 'NOTFOUND'
const SERVER = 'SoMeThiNg WenT wROng! TrY agaIN PLOXX! :P'

module.exports = { AUTHENTICATION, VALIDATION, NOTFOUND, SERVER }
