export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_SIGNUP_ERRORS = "SET_SIGNUP_ERRORS";
export const REMOVE_SIGNUP_ERROR = "REMOVE_SIGNUP_ERROR";
export const REMOVE_SIGNUP_ERRORS = "REMOVE_SIGNUP_ERRORS";
