export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const SET_FORM_ERRORS = "SET_FORM_ERRORS";
export const REMOVE_FORM_ERROR = "REMOVE_FORM_ERROR";
export const REMOVE_FORM_ERRORS = "REMOVE_FORM_ERRORS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const REMOVE_PROFILE_ERROR = "REMOVE_PROFILE_ERROR";
export const SET_PROFILE = "SET_PROFILE";
export const CLEAR_PROFILES = "CLEAR_PROFILE";
export const RESET_PROFILE_ERRORS = "RESET_PROFILE_ERRORS";

export const CREATE_POST = "CREATE_POST";
export const GET_POST_BY_ID = "GET_POST_BY_ID";
export const REMOVE_POST_BY_ID = "REMOVE_POST_BY_ID";
export const GET_POSTS_BY_USER = "GET_POSTS_BY_USER";
export const REMOVE_POSTS_BY_USER = "REMOVE_POSTS_BY_USER";
export const GET_POSTS_FROM_FOLLOWING = "GET_POSTS_FROM_FOLLOWING";
export const SET_POSTS_FROM_FOLLOWING = "SET_POSTS_FROM_FOLLOWING";
export const GET_CURRENT_USER_POSTS = "GET_CURRENT_USER_POSTS";
export const REMOVE_ALL_POSTS = "REMOVE_ALL_POSTS";
export const POST_ERROR = "POST_ERROR";

export const LOGOUT = "LOGOUT";

export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
